
package me.hch.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloServiceImplService", targetNamespace = "http://service.hch.me/", wsdlLocation = "file:/E:/tmp/ws-server-samples/wsimport-sample/src/main/webapp/WEB-INF/hello.wsdl")
public class HelloServiceImplService
    extends Service
{

    private final static URL HELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(me.hch.service.HelloServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = me.hch.service.HelloServiceImplService.class.getResource("");
            url = new URL(baseUrl, "file:/E:/tmp/ws-server-samples/wsimport-sample/src/main/webapp/WEB-INF/hello.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/tmp/ws-server-samples/wsimport-sample/src/main/webapp/WEB-INF/hello.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(HELLOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.hch.me/", "HelloServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort() {
        return super.getPort(new QName("http://service.hch.me/", "HelloServiceImplPort"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hch.me/", "HelloServiceImplPort"), HelloService.class, features);
    }

}
